//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLoginCode.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseDetail()
        {
            this.Feepayments = new HashSet<Feepayment>();
        }
    
        public int Course_Id { get; set; }
        public string Course_Name { get; set; }
        public string Course_Description { get; set; }
        public Nullable<int> Course_Fee { get; set; }
        public string FacultyName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feepayment> Feepayments { get; set; }
    }
}
