//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLoginCode.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feepayment
    {
        public int PaymentId { get; set; }
        public Nullable<int> Student_Id { get; set; }
        public Nullable<int> Course_Id { get; set; }
        public Nullable<int> CourseFee { get; set; }
        public string Course_Name { get; set; }
        public Nullable<int> Paid_Fee { get; set; }
        public Nullable<int> Pending_Fee { get; set; }
        public string Payment_Date { get; set; }
        public string Payment_Status { get; set; }
    
        public virtual CourseDetail CourseDetail { get; set; }
        public virtual StudentDetail StudentDetail { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
