//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLoginCode.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public string PaymentMode { get; set; }
        public string Credit_Debit { get; set; }
        public string NetBanking { get; set; }
        public string UPIPayment { get; set; }
        public string Nameoncard { get; set; }
        public string CreditCardNumber { get; set; }
        public string ExpMonth { get; set; }
        public Nullable<int> ExpYear { get; set; }
        public string CVV { get; set; }
    
        public virtual Feepayment Feepayment { get; set; }
    }
}
