//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLoginCode.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentDetail()
        {
            this.Feepayments = new HashSet<Feepayment>();
        }
    
        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string DateofBirth { get; set; }
        public string Gender { get; set; }
        public string CollegeName { get; set; }
        public string HallTicketNumber { get; set; }
        public string GuardianName { get; set; }
        public string GuardianContactNumber { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }
        public string StudentName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feepayment> Feepayments { get; set; }
    }
}
